import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { NextThemeProvider } from "@/lib/providers/next-theme-provider";
import db from "@/lib/supabase/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    console.log(db);
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                >
                    {children}
                </NextThemeProvider>
            </body>
        </html>
    );
}
